{{- if and .Values.mongodb.install }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-mongodb"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
spec:
  strategy:
    type: Recreate
    # recreateParams:
    #   post:
    #     execNewPod:
    #       command:
    #       - /bin/sh
    #       - -c
    #       - mongo mongodb.companies.svc.cluster.local/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval="${MONGO_INIT_SCRIPT}"
    #     containerName: mongodb
    #     failurePolicy: ignore
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
      deploymentconfig: mongodb
      container: mongodb
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}"
        deploymentconfig: mongodb
        container: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: 27017
          protocol: TCP
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 3
          exec:
            command:
            - "/bin/sh"
            - "-i"
            - "-c"
            - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
              --eval="quit()"
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 30
          tcpSocket:
            port: 27017
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: "{{ .Values.appName }}-mongodb-connection"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: "{{ .Values.appName }}-mongodb-connection"
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: adminPassword
              name: "{{ .Values.appName }}-mongodb-connection"
        - name: MONGODB_DATABASE
          value: "{{ .Values.mongodb.database }}"
        - name: MONGO_INIT_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: companiesdb-init
              key: initdb.js 
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - name: "{{ .Values.appName }}-mongodb-data"
          mountPath: "/var/lib/mongodb/data"
        - mountPath: /var/lib/mongodb/data/scripts
          #subpath: initdb.js 
          name: companiesdb-init
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities: {}
          privileged: false
      volumes:
      - name: "{{ .Values.appName }}-mongodb-data"
        {{- if .Values.mongodb.persistent }}
        persistentVolumeClaim:
          claimName: "{{ .Values.appName }}-mongodb"
        {{- else }}
        emptyDir:
          medium: ''
        {{- end }}
      - name: companiesdb-init
        configMap:
          name: companiesdb-init
      restartPolicy: Always
      dnsPolicy: ClusterFirst
{{- end }}
