{{- if .Values.mongodb.install }}
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-mongodb-connection"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.mongodb.username }}"
data:
  {{- if .Values.mongodb.password }}
  password: {{ .Values.mongodb.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.adminPassword }}
  adminPassword: {{ .Values.mongodb.adminPassword | b64enc | quote }}
  {{- else }}
  adminPassword: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}