apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  name: bbank-repo
spec:
 # optional name that might be used by console
  name: Bbank Helm Charts
  connectionConfig:
    url:  https://mouachan.github.io/companies-catalog-helm