appName: companies-catalog-helm
apps:
  install: true
  javaopts: -Dvertx.cacheDirBase=/work/vertx
  image: quay.io/mouachan/companies-svc:custom
mongodb:
  install: true
  uri: companies-catalog-helm-mongodb:27017
  database: companies
  image: centos/mongodb-36-centos7:latest
  persistent: true
  volumeSize: 2Gi
  
  username: admcomp
  # Unless you uncomment following line, admin password will be randowly generated.
  # Beware that in case of update, new value will be generated and overwrite existing one.
  password: r3dh4t2021!

  # Or you can uncomment secretRef block if username and password are provided through a Secret.
  #secretRef:
    #secret: mongodb
    #usernameKey: database-user
    #passwordKey: database-password